import { ASSISTANCE_PROGRAMS_EDUCATION } from "./assistance-programs";
import { CALIFORNIA_2025_EDUCATION } from "./california-2025";
import { CALIFORNIA_PRE_1990_EDUCATION } from "./california-pre-1990";

export const EDUCATION_FLOW_DATA = {
  [CALIFORNIA_PRE_1990_EDUCATION.accessor]: CALIFORNIA_PRE_1990_EDUCATION,
  [CALIFORNIA_2025_EDUCATION.accessor]: CALIFORNIA_2025_EDUCATION,
  [ASSISTANCE_PROGRAMS_EDUCATION.accessor]: ASSISTANCE_PROGRAMS_EDUCATION,
};
